### ISSUE TITLE
Correction in the readme.md

### ISSUE THREAD

**Issue by kritixilithos** [alexander-liao/proton#2]
> If you are on Windows or MacOS, you may need to change it to `proton.py` and run it with `python proton.py <filename> [args...]`.

That is not the case in macOS. If `proton` is an executable, then doing `./proton` will run it using the `python3` interpreter.

(just wanted to point that out :P)

**Comment by hyperneutrino** [comment]
Oh ok :P Do you know if it works in Windows?

**Comment by hyperneutrino** [comment]
Done, thanks for the correction :P :)

**Comment by kritixilithos** [comment]
I don't have Windows, so I can't test it there.

**Comment by pavelbraginskiy** [comment]
On Windows, you would change it to proton.py, but invoke it as ./proton anyway. Windows determines the interpreter to run the code with by the extension.

**Comment by somebody1234** [comment]
@pavelbraginskiy Well I always thought you normally do `proton.py` on Windows
