### ISSUE TITLE
Reduce returns a function

### ISSUE THREAD

**Issue by totallyhuman** [alexander-liao/proton#3]
When the built-in function `reduce` (the implementation of which is [here](https://github.com/alexander-liao/proton/blob/master/lang.proton#L21-L28)) is used, it always returns a function. I dunno what else to say, but expected behaviour is to return some data of any other type. :P

The string representation of the function returned (`<utils.Function object at 0xsomething>`) hints to the fact that the function returned is an instance of the [`Function` class](https://github.com/alexander-liao/proton/blob/master/utils.py#L90-L145) from [utils.py](https://github.com/alexander-liao/proton/blob/master/utils.py), though I'm not sure how that can help.

[Try it online!](https://tio.run/##KyjKL8nP@/@/JLW4RMFWoSg1pTQ5VUOjQkehUlPB1k6hQkFboVJHoSgxLz1Vw1RTk4uroCgzr0QDpF4Txq4sSIUIaCLJaqDxQFDz/38A "Proton – Try It Online")

**Comment by hyperneutrino** [comment]
I think this got fixed at some point in time as a byproduct of me fixing other bugs. [Example of correct usage](https://tio.run/##KyjKL8nP@/@/oCgzr0SjKDWlNDlVQyNRRyFJU8HWTiFRQVshSUch2lBHwUhHwThWU/P/fwA) I'll leave this issue open for a bit, and if you find any other bugs with other functions, please let me know. Thanks! @totallyhuman

**Comment by hyperneutrino** [comment]
https://tio.run/##KyjKL8nP@/@/SMFWoSg1pTQ5VUMjUUchSVPB1k4hUUEbyOLiKijKzCvRKEKwNKINdRSMdBSMYzU1//8HAA

**Comment by somebody1234** [comment]
[Golfed](https://tio.run/##KyjKL8nP@/@/oCgzr0SjKDWlNDlVQ0NbUyfaUMdIxzhWU/P/fwA) Maybe add `Function.__rdiv__` too :P so `[1,2,3]/(+)` works

**Comment by hyperneutrino** [comment]
@somebody1234 I will look into that idea. :P
