### ISSUE TITLE
Bitwise operators no longer work

### ISSUE THREAD

**Issue by hyperneutrino** [alexander-liao/proton#5]
After moving to using `sympy` values, bitwise operators no longer work. Bitwise operators need implicit `int` calls.

**Comment by somebody1234** [comment]
:|

**Comment by somebody1234** [comment]
Why `int` calls? Why not just keep them as `sympy` values?

**Comment by hyperneutrino** [comment]
@somebody1234 `sympy` doesn't support bitwise? I could override bitwise to use normal arithmetic but I prefer to use the actual bitwise.
